### ISSUE TITLE
Crashes on Xcode 11

### ISSUE THREAD

**Issue by Reckoner1710** [oronbz/RxGithub#1]
Swift class extensions and categories on Swift classes are not allowed to have +load methods

**Comment by oronbz** [comment]
Thanks for that! Will be fixed really soon!

**Comment by oronbz** [comment]
Hi @Reckoner1710, this should be fixed now with this commit https://github.com/oronbz/RxGithub/commit/eb9f362fcaa47bfdb58d60efed64a47e4dc4a35d
